#INCLUDE P16F84A.INC
    PIN_CODE_ADDRESS EQU 0X20
    PIN_COUNTER_ADDRESS EQU 0X21 
    PIN_CODE EQU B'00000101'
    PIN_COUNTER EQU 0X03 
    COUNTL EQU 0X22 
    COUNTH EQU 0X23 
    COUNTER1m_ADDRESS EQU 0X24 
    COUNTER1m EQU 0X0A 
    VALUE_ADDRESS EQU 0X25
    FLASH_COUNTER EQU 0X03 
    FLASH_COUNTER_ADDRESS EQU 0X26 
    COUNTER1S EQU 0X0F 
    COUNTER1SH EQU 0X01
    COUNTER1SH_ADDRESS EQU 0X27
    COUNTER1S_ADDRESS EQU 0X28
    ORG 0X00 
    GOTO INIT 
    
    
    
    
    INIT 
   ;INIT FOR PORTS  
    BANKSEL TRISA 
    MOVLW B'00001111' 
    MOVWF TRISA 
    MOVLW B'00010011'
    MOVWF TRISB 
    BANKSEL PORTA 
    CLRF PORTB
    CLRF PORTA 
   
    
    ;------------------------------INIT------------------------------------;
    ;INIT DELAY COUNTER 
    MOVLW COUNTER1m
    MOVWF COUNTER1m_ADDRESS
    
    ;INTI FLASH COUNTER 
    MOVLW FLASH_COUNTER 
    MOVWF FLASH_COUNTER_ADDRESS 
    
    ;INIT DELAY 1 SECOND COUNTERS 
    MOVLW COUNTER1S 
    MOVWF COUNTER1S_ADDRESS 
    MOVLW COUNTER1SH
    MOVWF COUNTER1SH_ADDRESS 
    
    ;SAVING PIN CODE IN EEPROM 
    BANKSEL EEADR ;  
    MOVLW PIN_CODE_ADDRESS ; ADDRESS IN EEPROM 
    MOVWF EEADR 
    MOVLW PIN_CODE 
    MOVWF EEDATA
    BANKSEL EECON1 
    CLRF EECON1 
    BSF EECON1 , 2 
    MOVLW 0X55 
    MOVWF EECON2 
    MOVLW 0XAA 
    MOVWF EECON2 
    BSF EECON1 , 1 
    MOVF EECON1 , W 
    CALL TenMs
    ;END OF INIT 
    
    ;-------------------------------MAIN------------------------------------;
    MAIN   
    CALL CHECK_PIN 
    CALL CUSTOMER_ACTION 
    CALL TenMs
    CALL CHECK_FEEDBACK 
    ; PROGRAM FINISHED 
    GOTO MAIN

    ;---------------------------SUBROUTINES------------------------------;
    ;CHECKING IF TRANSACTION DONE SUCCESSFULLY OR NOT  
    CHECK_FEEDBACK 
	BANKSEL PORTB 
	BTFSS PORTB , 4 
	GOTO FLASHING_LED
	BSF PORTB , 2 
    RETURN 
    
    ;WITHDRAW / DEPOSIT SUBROUTINE 
    CUSTOMER_ACTION
	
	BANKSEL PORTB 
	BUTTON	
    	BTFSS PORTB , 1
	GOTO BUTTON 
	CALL Onems
	BTFSS PORTB , 0 
	GOTO WITHDRAW	
	GOTO DEPOSIT

    DEPOSIT
	BANKSEL PORTA 
	MOVF PORTA , W 
	MOVWF VALUE_ADDRESS
	BTFSC VALUE_ADDRESS , 0 
	GOTO TRY_AGAIN
	BTFSC VALUE_ADDRESS , 1 
	GOTO TRY_AGAIN
	
	SWAPF VALUE_ADDRESS ,1
	BSF VALUE_ADDRESS , 3 
	BSF VALUE_ADDRESS , 5 
	MOVF VALUE_ADDRESS , W 
	BANKSEL PORTB 
	MOVWF PORTB
	CALL Onems
	RETURN 
    TRY_AGAIN 
	CALL FLASHING_LED 
	GOTO BUTTON
    RETURN
	
    
    WITHDRAW 	
	BANKSEL PORTA 
	MOVF PORTA , W 
	MOVWF VALUE_ADDRESS 
	BTFSC VALUE_ADDRESS , 0 
	GOTO TRY_AGAIN
	BTFSC VALUE_ADDRESS , 1 
	GOTO TRY_AGAIN2
	
	SWAPF VALUE_ADDRESS ,1
	BCF VALUE_ADDRESS , 3 
	BSF VALUE_ADDRESS , 5 
	MOVF VALUE_ADDRESS , W 
	MOVWF PORTB 
	RETURN 
    TRY_AGAIN2 
	CALL FLASHING_LED 
	GOTO BUTTON
     	
    RETURN 
	

	
    ;CHECKING PIN CODE SUBROUTINE 
    CHECK_PIN 
	BANKSEL PORTA 
	_BUTTON	
    	BTFSS PORTB , 1
	GOTO _BUTTON
	CALL Onems
	;READING PINCODE FROM EEPROM 
	BANKSEL EEADR
	MOVLW PIN_CODE_ADDRESS 
	MOVWF EEADR 
	BANKSEL EECON1 
	BSF EECON1 , 0 
	BANKSEL EEDATA 
	MOVF EEDATA, W 
	; MAKING SURE THAT THE ENTERED PIN CODE IS RIGHT 
	SUBWF PORTA , W 
	BTFSC STATUS , Z 
	RETURN 
	DECFSZ PIN_COUNTER_ADDRESS,1
	GOTO CHECK_PIN
    INF	    GOTO INF ;PROGRAM EXITS AFTER 3 WRONG PIN
    
    
    FLASHING_LED 
    FLASH
	;BIT RB3 SHOULD TELL THE OTHER PIC THE CUSTOMER ACTION 
	;TO DO FLASHING WE NEED TO MAKE RB4-RB7 INPUTS SO WE DON'T SEND TO THE OTHER
	;PIC RUBISH VALUES .. 
	;BANKSEL TRISB 
	;MOVLW B'11111011'
        ;MOVWF TRISB 
	BANKSEL PORTB
	BSF PORTB , 2
	CALL Onems 
	BANKSEL PORTB
	BCF PORTB , 2 
	CALL Onems 
	DECFSZ FLASH_COUNTER_ADDRESS , 1 
	GOTO FLASH 
	;BANKSEL TRISB	
	;MOVLW B'00000011'
	;MOVWF TRISB 
	MOVLW FLASH_COUNTER 
	MOVWF FLASH_COUNTER_ADDRESS 
    RETURN 
    
    RETURN 
    ;10 ms SUBROUTINE 
    TenMs nop; beginning of subroutine
	movlw D'13'
	movwf COUNTH
	movlw D'250'
	movwf COUNTL
	Ten1 decfsz COUNTL , F; inner loop
	goto Ten1
	decfsz COUNTH , F ; outer loop
	goto Ten1
    return

;1 ms SUBROUTINE 
Onems  
    DELAY 
    CALL TenMs
    DECFSZ COUNTER1m_ADDRESS , 1 
    GOTO DELAY 
    MOVLW COUNTER1m
    MOVWF COUNTER1m_ADDRESS
RETURN 
Ones 
    DELAY1S 
    CALL Onems
    DECFSZ COUNTER1S_ADDRESS,1
    GOTO DELAY1S
    ;DECFSZ COUNTER1SH_ADDRESS , 1 
    ;GOTO DELAY1S 
    MOVLW COUNTER1S
    MOVWF COUNTER1S_ADDRESS
    MOVLW COUNTER1S 
    MOVWF COUNTER1S_ADDRESS 
    
RETURN 
END
